### ISSUE TITLE
Where can I find calibration and pose data?

### ISSUE THREAD

**Issue by prclibo** [jotaraul/robot-at-home_meeting-point#2]
Hi, thanks for providing this dataset.

I downloaded some data and didn't find the calibration data on either the intrinsics and the extrinsics. 

In addition, I noticed in the txt file accompanied with each rgbd data folder (e.g. bathroom1_rgbd.txt), the sensor pose data (x, y, z, roll, pitch, yaw) are all zeros.

So can anyone please let me know what to do if I need to the calibration and pose data for some 3D reconstruction research?

Thanks!

**Comment by jotaraul** [comment]
Dear @prclibo,

You're welcome! I hope the datastet could be useful for you :)

Regarding the calibration data, I've included them into the dataset webpage (calibration parameters section): 

http://mapir.uma.es/mapirwebsite/index.php/mapir-downloads/203-robot-at-home-dataset.html

Regarding the sensor pose data, please notice that the data come both raw, and processed. In this way, the data within the "Labeled RGB-D data" column include such sensor pose data.

Hope this helps!

Best regards

**Comment by prclibo** [comment]
@jotaraul Thanks for the reply.

I found and played a while with the pose in the labeled rgbd data you mentioned and was still confused on how the pose data is defined. Could you please give some hints?

Take, say anto-s1/bathroom2_labelled.txt as an example. I observe that when robot is moving along x, the `sensor_pose_yaw` of RGBD_1 is aprox -0.78, implying that RGBD_1 is a camera looking at 45deg from forward. But your updated extrinsics says RGBD_1 is pointing right forward.

In addition, in the RGBD data x corresponds the the world vertical direction z. However, I tried several Euler-angle transformation and cannot get rotation which can transform between x and z.

Could you please also share how the yaw/pitch/roll is interpreted in this dataset? For a 3d point in the frame of the RGBD camera x_c and its corresponding world point x_w, how can I construct the sensor pose [R, t] s.t. x_w = R * x_c + t from a line of the labelled.txt?

Thanks again.

**Comment by jotaraul** [comment]
@prclibo let's see:

> I found and played a while with the pose in the labeled rgbd data you mentioned and was still confused on how the pose data is defined. Could you please give some hints?
>

I noticed that the calibration provided was not complete! I mean, the dataset was collected mainly in two different periods, and the ids of the RGBD cameras changed from one to other. I've clarified that, please check the [webpage again](http://mapir.uma.es/mapirwebsite/index.php/mapir-downloads/203-robot-at-home-dataset.html).

> Take, say anto-s1/bathroom2_labelled.txt as an example. I observe that when robot is moving along x, the `sensor_pose_yaw` of RGBD_1 is aprox -0.78, implying that RGBD_1 is a camera looking at 45deg from forward. But your updated extrinsics says RGBD_1 is pointing right forward.
> 

Please notice that the poses in that files are poses w.r.t. the world frame (the map), i.e., they are absolute poses, not poses w.r.t. the local robot frame. 

> In addition, in the RGBD data x corresponds the the world vertical direction z. However, I tried several Euler-angle transformation and cannot get rotation which can transform between x and z.
> 
> Could you please also share how the yaw/pitch/roll is interpreted in this dataset? For a 3d point in the frame of the RGBD camera x_c and its corresponding world point x_w, how can I construct the sensor pose [R, t] s.t. x_w = R * x_c + t from a line of the labelled.txt?
> 

I also included in the webpage the reference system used, including the angles. For the answer being self-contained:

![image](https://user-images.githubusercontent.com/8874841/54595886-d5119e80-4a33-11e9-8f92-0b7094b77a0c.png)
More info also here: https://www.mrpt.org/tutorials/programming/maths-and-geometry/2d_3d_geometry/

For obtaining the coordinates of a point **i** in the world frame, you have to compose the observation pose and the point x,y,z coordinates computed in the following way:

x(i) = value_of_pixel_i*(1/6,553.5); 
y(i) = (cx - c) * x(i) / fx 
z(i) = (cy - r) * x(i) / fy 

Where value_of_pixel_i is the value of pixel i in the depth image.

Let me know if this makes sense for you :)

**Comment by prclibo** [comment]
@jotaraul Thanks for the quick reply.

Let me use the following example to illustrate my second question:

I took obs_id of 1 and 36 from `anto-s1/bedroom1_labelled` on RGBD_4, which is forward looking to simplify the problem.

    4 RGBD_4 0.283666 -0.000742568 1.00555 0.0147668 -0.000738024 -1.54087 130986284270791005
    144 RGBD_4 0.399775 0.0205408 0.982538 0.0797461 -0.0020064 -1.53712 130986284303551063

The sensor_poses are computed as follows, under https://www.mrpt.org/tutorials/programming/maths-and-geometry/2d_3d_geometry/#24_CPose3D_xyzyawpitchroll

    0.9999    0.0003   -0.0148    0.2837
    0.0148    0.0299    0.9994   -0.0007
    0.0007   -0.9996    0.0299    1.0055
    
    0.9968   -0.0007   -0.0797    0.3998
    0.0797    0.0337    0.9963    0.0205
    0.0020   -0.9994    0.0337    0.9825

From obs_id 1 to 36, the robot is moving along world frame x-axis (0.28->0.39). The above matrices implies that the sensor frame x-axis is aligning with world frame x-axis (because R(0, 0) ~ 1). Assuming that the robot is moving forward, the x-axis of RGB_4 is pointing forward. However, as a camera should always have z-axis pointing forward.

So my question is if I am missing any extrinsics relating RGB_4 forward direction between x-axis and z-axis.

**Comment by jotaraul** [comment]
@prclibo I think that the point is: 

> However, as a camera should always have z-axis pointing forward.

The information I provided you was to obtain the coordinates in the same representation as the robot pose, that is, with the x-axis looking forwards. You can interpret the information in the depth image with the common camera reference frame, with z-axis pointing forward, but then you need to apply an additional transformation to place the 3D points in the world coordinates. In the past, to convert from MRPT to PCL coordinates (z towards, x to the right, y downwardsI used the following matrix, i guess you need the inverse, depending on the reference system you want to use:

    transMat(0,0)=0;    transMat(0,1)=-1;     transMat(0,2)=0;    transMat(0,3)=0;
    transMat(1,0)=0;    transMat(1,1)=0;      transMat(1,2)=+1;   transMat(1,3)=0;
    transMat(2,0)=1;    transMat(2,1)=0;      transMat(2,2)=0;    transMat(2,3)=0;
    transMat(3,0)=0;    transMat(3,1)=0;      transMat(3,2)=0;    transMat(3,3)=1;

Hope this helps!

**Comment by prclibo** [comment]
@jotaraul Thanks for this hint.

I think I got it work by using the following transformation

     0     0     1     0
    -1     0     0     0
     0    -1     0     0
     0     0     0     1

I put my Matlab code here in case someone can use it.

    cam_extrs = [0, 0, 1, 0; -1, 0, 0, 0; 0, -1, 0, 0; 0, 0, 0, 1];
    gt_pose = eye(4);
    gt_pose(1:3, 1:3) = angle2dcm(yaw, pitch, roll)'; % direct reading from txt
    gt_pose(1:3, 4) = [x; y; z]; % direct reading from txt
    gt_pose = gt_pose * cam_extrs;

**Comment by jotaraul** [comment]
@prclibo great! Please, let us know any interesting results you could get using the dataset!

**Comment by prclibo** [comment]
@jotaraul Yes, we will.

Your calibration intrinsics still looks weird. Using your focal length ~570 gives skew RGBD point cloud. Using your focal/2 seems to work.

According to your paper, the RGBD FoV is 58x45deg, should be ~280.

**Comment by jotaraul** [comment]
@prclibo 

> @jotaraul Yes, we will.

Nice! :)
 
> Your calibration intrinsics still looks weird. Using your focal length ~570 gives skew RGBD point cloud. Using your focal/2 seems to work.
> 
> According to your paper, the RGBD FoV is 58x45deg, should be ~280.

You're totally right. That focal lengths are expressed in pixels, and has to be half of the ones given in the webpage. The cameras were calibrated with 640x480 resolution, but the images where stored with 320x240, that's why I also scaled the centers, but forgot to do that with the focal lengths. I'm going to modify it, 

Thank you for your comments :)
