### ISSUE TITLE
Problem downloading datasets

### ISSUE THREAD

**Issue by laurago894** [jotaraul/robot-at-home_meeting-point#3]
Hi!

Thanks for sharing these datasets. However, I was unable to download  them ( going to the Downloads section and clicking on the F and P icons). Did I maybe missunderstand how/where to download them?

Thanks!

Laura

**Comment by jotaraul** [comment]
Hi @laurago894 !

First of all, thank you for your interest! :) You're right, for some reason the downloads are not working. Maybe the downloads' server is down. Let me check it tomorrow and I'll be back to you with (hopefully) good news :)

Best,
Raúl.

**Comment by laurago894** [comment]
Thank you for the prompt reply!

**Comment by jotaraul** [comment]
You're welcome! Try to download it now, it should work :) Let me know if everything is fine please!

Best,
Raúl.

**Comment by laurago894** [comment]
It's working now! Thanks!
