### ISSUE TITLE
cartographer and hector_slam cannot generate correct map for sarmis

### ISSUE THREAD

**Issue by qixianyu-buaa** [jotaraul/robot-at-home_meeting-point#4]
Hi, thanks very much for providing the dataset.

I want to run the laser scans with ROS.

I convert the plain text to rosbag and the cartographer and hector_slam are both drift very much with the sarmis.

I want to know how to generate the correct map, or do you have the message from odometry?

By the way, what the difference with the 1_hokuyo_processed and 2_hokuyo_processed in the alma? When I build the map, if I should only use one of them?

Thank you!

**Comment by jotaraul** [comment]
Dear @qixianyu-buaa,

Sorry for the late reply! We're having a weird situation, as you know :)

The observations from the laser scanner where saved at a lower frequency in sarmis than in the rest of houses, so I reckon those methods could experience difficulties building maps from them. Have you tried gmapping? 

Regarding the 1_hokuyo_processed and  2_hokuyo_processed, they are just two sequences of laser data from the same place, so with one of them should be enough.

Hope this helps!

**Comment by qixianyu-buaa** [comment]
Dear @jotaraul,

First of all, thanks for your reply.

I have built the map with the cartographer successfully in other datasets, however, when I tried cartographer, hector SLAM, and MRPT ICP SLAM, all of them failed in the sarmis.
I want to try the gmapping, but it needs the message from encoders. 
I think if the dataset provides the wheel odometry message,  all methods can build the map successfully.

Now, I want to use the RGB-D data to build the map and get the trajectory,  then I can use the trajectory to build the laser map. I have tried the ORB-SLAM2 with one camera, but it failed. The environment is very challenging and needs to use four cameras.

So, What's the method you used to build the 3d point clouds? Is it open-source?

Thank you!

**Comment by jotaraul** [comment]
Dear @qixianyu-buaa,

> I have built the map with the cartographer successfully in other datasets, however, when I tried cartographer, hector SLAM, and MRPT ICP SLAM, all of them failed in the sarmis.
> I want to try the gmapping, but it needs the message from encoders.
> I think if the dataset provides the wheel odometry message, all methods can build the map successfully.

Unfortunately, the wheel encoders of the robot used to gather the dataset were so bad, and we directly discarded that information.

> Now, I want to use the RGB-D data to build the map and get the trajectory, then I can use the trajectory to build the laser map. I have tried the ORB-SLAM2 with one camera, but it failed. The environment is very challenging and needs to use four cameras.
> 
> So, What's the method you used to build the 3d point clouds? Is it open-source?

We relied on a modification of DIFODO to work with the 4 cameras, which is integrated in the Object Labeling Toolkit (third_party/difodo_multi): https://github.com/jotaraul/Object-Labeling-Toolkit 

Hope this helps!

**Comment by qixianyu-buaa** [comment]
Dear @jotaraul,

I will try the DIFODO and thanks very much for your help.
