### ISSUE TITLE
Where can I find the camera poses in time orders like  "fullhouse1_rgbd.txt"?

### ISSUE THREAD

**Issue by qixianyu-buaa** [jotaraul/robot-at-home_meeting-point#5]
Dear @jotaraul,

I have tried to compile the Object Labeling Tool but failed. 
I think I cannot compile and use it successfully in a short time.
Now I want to get the camera poses in the time orders like the fullhouse1_rgbd.txt? For example, I can find the "fullhouse1_rgbd.txt" in the **raw** data-plain_text-pare-s1, However, this file is not in **labelled** rgbd-data_plain-text_pare-s1. While I found the labeled files are organized by rooms, I want the camera poses organized like "fullhouse1_rgbd.txt".

Could you tell me where I can find it or Would you like to provide the file? 

Thank you!

Best regards.

**Comment by jotaraul** [comment]
Dear @qixianyu-buaa,

> I have tried to compile the Object Labeling Tool but failed.
> I think I cannot compile and use it successfully in a short time.

I reckon you don't need to compile the full OLT thing. You can just take "third_pary/difodo_multi", which depends on MRPT and Eigen, and then take inspiration from "apps/mapping.cpp" to use it.

> Now I want to get the camera poses in the time orders like the fullhouse1_rgbd.txt? For example, I can find the "fullhouse1_rgbd.txt" in the **raw** data-plain_text-pare-s1, However, this file is not in **labelled** rgbd-data_plain-text_pare-s1. While I found the labeled files are organized by rooms, I want the camera poses organized like "fullhouse1_rgbd.txt".

I see your point, but the sequences covering full houses are not labelled, just those from single rooms. It would be valuable data, but it's not available at the moment.

Best regards.

**Comment by qixianyu-buaa** [comment]
Dear @jotaraul ,

Thanks very much for your advice, and I will try it.

Best regards.
