### ISSUE TITLE
Download datasets

### ISSUE THREAD

**Issue by cristianl1251** [jotaraul/robot-at-home_meeting-point#8]
Hi,

I'm having issues downloading the datasets. Can you check if the downloads' server is down?

Thank you.

**Comment by jotaraul** [comment]
Dear @cristianl1251 ,

We are migrating our server, and moved the dataset to Zenodo. Please find it here: https://zenodo.org/record/4530453#.YcGsMmjMKUk

We will edit the dataset homepage and add that link ASAP.

Thank you for your interest.
Best regards.

**Comment by cristianl1251** [comment]
Dear @jotaraul,

Thank you for your response. I was able to download the datasets in Zenodo.

Best Regards.

**Comment by jotaraul** [comment]
Super!

Best regards.
